// Generated by CoffeeScript 1.4.0
(function() {
  var Schema, bookSchema, mongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  bookSchema = mongoose.Schema({
    title: String,
    authors: [String],
    isbn: String,
    location: String,
    lender: {
      email: String
    },
    image: String,
    description: String
  });

  module.exports = mongoose.model('Books', bookSchema);

}).call(this);
